{
  "_annotation": {
    "cve_id": "CVE-2024-28233",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-28233.json",
    "triage_notes": {
      "references": [
        "https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-7r3h-4ph8-w38g",
        "https://github.com/jupyterhub/jupyterhub/commit/e2798a088f5ad45340fe79cdf1386198e664f77f"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:jupyterhub:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "20814D5A-20FA-5589-9FC1-919B7C71D1E0",
                "versionEndExcluding": "4.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}