{
  "_annotation": {
    "cve_id": "CVE-2024-28865",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-28865.json",
    "triage_notes": {
      "references": [
        "https://github.com/django-wiki/django-wiki/security/advisories/GHSA-wj85-w4f4-xh8h",
        "https://github.com/django-wiki/django-wiki/commit/8e280fd6c0bd27ce847c67b2d216c6cbf920f88c"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:django-wiki_project:django-wiki:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "71E9C2B2-6AB6-5866-9E21-AC86EC234323",
                "versionEndExcluding": "0.10.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}